### ISSUE TITLE
Upgrade to latest version

### ISSUE THREAD

**Issue by mariobehling** [FOSSASIA-Web/perspektive89.com#1]

**Comment by namangoel1** [comment]
Done.

**Comment by namangoel1** [comment]
Seems like this is not moved to the server, though. I guess it would be good to create a new issue for that?

**Comment by mariobehling** [comment]
https://github.com/fossasia/perspektive89.com/issues/2

**Comment by tradzik** [comment]
@mariobehling Can you explain me these work with new repos? Can I participate in it and help too?

**Comment by tradzik** [comment]
@namangoel1 Or you?

**Comment by mariobehling** [comment]
@ty221 Yes, would be great, if you can help here. The current issues are a continuation of tasks Namanyay did before. There will be more coming up in the next few days. In the meantime, what would be great is to get the left over content from 2010.fossasia.org , e.g. Vietnamese content into the github page, but we should follow up on the issues there - not in this thread here.

**Comment by mariobehling** [comment]
Pictures not yet working on new site: http://perspektive89.com

**Comment by mariobehling** [comment]
@ty221 Would you be interested to make the image working on this Drupal7 site? It is probably just a simple files directory issue. (http://perspektive89.com/?q=admin/reports/status)

**Comment by tradzik** [comment]
@mariobehling Yes I can help you with that. Please mail me with server login data

**Comment by tradzik** [comment]
@mariobehling I am sorry. I was away for few days and couldn't work on these issues. I am starting tomorrow :-)

**Comment by tradzik** [comment]
@mariobehling Problem has been fixed. Files of images weren't present on server. I moved them from old host to current one and now website should work properly.

**Comment by mariobehling** [comment]
Well-done. Very good! Cheers.

**Comment by mariobehling** [comment]
Well-done. Very good! Cheers.
